version: "3.1"
#docker save --output vuce2-mfeconfig-api.tar vuce2-mfeconfig-api:0.1-SNAPSHOT
#docker load --input  vuce2-mfeconfig-api.tar
services:
  vuce2-mfeconfig-api:
    image: vuce2-mfeconfig-api:0.1-SNAPSHOT
    container_name: vuce2-mfeconfig-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8083:8000"
    environment:
      API_PORT: 8000
      MONGO_HOST: 10.19.34.185
      MONGO_PORT: 32465
      MONGO_DB: frontendConfig
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password
      ELK_HOST: localhost
      ELK_PORT: 5000
    volumes:
      - ./log:/app/log
    networks:
      - backend
networks:
  backend:
    external: true